version: "3"

services:
  game:
    build: .
    volumes:
#      - ./Server/lib:/app/Server/lib/
      - ./Server/lib/sub/:/app/Server/lib/sub/
      - ./Server/Cert/:/app/Cert
    depends_on:
      - db
    command: [ "node", "/app/Server/lib/Game/cluster.js", "0", "1" ]
    restart: always
    ports:
      - 110:110
      - 8496:8496
      - 8110:8110
      - 8080:8080
  web:
    build: .
    volumes:
#      - ./Server/lib:/app/Server/lib/
      - ./Server/lib/sub/:/app/Server/lib/sub/
      - kkutu_data:/kkutu
      - ./Server/Cert/:/app/Cert
    command: [ "node", "/app/Server/lib/Web/cluster.js", "1" ]
    restart: always
    depends_on:
      - db
      - game
    ports:
      - 80:80
  db:
    build:
      context: .
      dockerfile: ./psql.Dockerfile
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
#      - 5432:5432

volumes:
  kkutu_data:
  db_data:
